/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hsa_jni_hsa_jni_WekaHSAContext_SGD */

#ifndef _Included_hsa_jni_hsa_jni_WekaHSAContext_SGD
#define _Included_hsa_jni_hsa_jni_WekaHSAContext_SGD
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hsa_jni_hsa_jni_WekaHSAContext_SGD
 * Method:    UpdateWeights
 * Signature: (Lhsa_jni/hsa_jni/InstanceBatch;[D)V
 */
JNIEXPORT void JNICALL Java_hsa_1jni_hsa_1jni_WekaHSAContext_00024SGD_UpdateWeights
  (JNIEnv *, jobject, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
