/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hsa_jni_hsa_jni_WekaHSAContext_KnnNativeContext */

#ifndef _Included_hsa_jni_hsa_jni_WekaHSAContext_KnnNativeContext
#define _Included_hsa_jni_hsa_jni_WekaHSAContext_KnnNativeContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hsa_jni_hsa_jni_WekaHSAContext_KnnNativeContext
 * Method:    knn
 * Signature: ([D[D[DIII[D[I)V
 */
JNIEXPORT void JNICALL Java_hsa_1jni_hsa_1jni_WekaHSAContext_00024KnnNativeContext_knn
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint, jdoubleArray, jintArray);

/*
 * Class:     hsa_jni_hsa_jni_WekaHSAContext_KnnNativeContext
 * Method:    rescanRanges
 * Signature: ([D[DIIII)V
 */
JNIEXPORT void JNICALL Java_hsa_1jni_hsa_1jni_WekaHSAContext_00024KnnNativeContext_rescanRanges
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
