/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hsa_jni_hsa_jni_InstanceBatch */

#ifndef _Included_hsa_jni_hsa_jni_InstanceBatch
#define _Included_hsa_jni_hsa_jni_InstanceBatch
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
