/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hsa_jni_hsa_jni_WekaHSAContext */

#ifndef _Included_hsa_jni_hsa_jni_WekaHSAContext
#define _Included_hsa_jni_hsa_jni_WekaHSAContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hsa_jni_hsa_jni_WekaHSAContext
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hsa_1jni_hsa_1jni_WekaHSAContext_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
