//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 08:29:13 PM NZDT 
//


package hsa_jni.hsa_jni.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hsa_jni.hsa_jni.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hsa_jni.hsa_jni.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FirstKnnExperiment }
     * 
     */
    public FirstKnnExperiment createFirstKnnExperiment() {
        return new FirstKnnExperiment();
    }

    /**
     * Create an instance of {@link SGDExperiment }
     * 
     */
    public SGDExperiment createSGDExperiment() {
        return new SGDExperiment();
    }

    /**
     * Create an instance of {@link Experiments }
     * 
     */
    public Experiments createExperiments() {
        return new Experiments();
    }

}
