//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 08:29:13 PM NZDT 
//


package hsa_jni.hsa_jni.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SGDExperiment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SGDExperiment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="window" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="test_size" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="train_size" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="generator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="train_batch" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="test_batch" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SGDExperiment", propOrder = {

})
public class SGDExperiment {

    protected int window;
    @XmlElement(name = "test_size")
    protected int testSize;
    @XmlElement(name = "train_size")
    protected int trainSize;
    @XmlElement(required = true)
    protected String generator;
    @XmlElement(name = "train_batch")
    protected int trainBatch;
    @XmlElement(name = "test_batch")
    protected int testBatch;

    /**
     * Gets the value of the window property.
     * 
     */
    public int getWindow() {
        return window;
    }

    /**
     * Sets the value of the window property.
     * 
     */
    public void setWindow(int value) {
        this.window = value;
    }

    /**
     * Gets the value of the testSize property.
     * 
     */
    public int getTestSize() {
        return testSize;
    }

    /**
     * Sets the value of the testSize property.
     * 
     */
    public void setTestSize(int value) {
        this.testSize = value;
    }

    /**
     * Gets the value of the trainSize property.
     * 
     */
    public int getTrainSize() {
        return trainSize;
    }

    /**
     * Sets the value of the trainSize property.
     * 
     */
    public void setTrainSize(int value) {
        this.trainSize = value;
    }

    /**
     * Gets the value of the generator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerator() {
        return generator;
    }

    /**
     * Sets the value of the generator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerator(String value) {
        this.generator = value;
    }

    /**
     * Gets the value of the trainBatch property.
     * 
     */
    public int getTrainBatch() {
        return trainBatch;
    }

    /**
     * Sets the value of the trainBatch property.
     * 
     */
    public void setTrainBatch(int value) {
        this.trainBatch = value;
    }

    /**
     * Gets the value of the testBatch property.
     * 
     */
    public int getTestBatch() {
        return testBatch;
    }

    /**
     * Sets the value of the testBatch property.
     * 
     */
    public void setTestBatch(int value) {
        this.testBatch = value;
    }

}
