package org.moa.gpu.bridge;

import weka.core.Instance;

/** 
 * NativeInstance -> an object generated by the stream generator or a wrapper for the normal WEKA instance
 * NativeInstance can be added to the BatchInstances - a sparse/dense matrix based collection which can be processed 
 * by the Native classifier
 * 
 * WEKA Classifier.trainOnInstance() may hide the fact that NativeInstances are created 
 * 
 * NativeInstance(NativeInstance) -> creates a clone of the natively allocated data
 * NativeInstance -> BatchInstances -> adds native data to BatchInstances matrix data
 * Instance -> BatchInstances  
 *
 */
public interface NativeInstance extends Instance {

}
