/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_gpu_bridge_NativeDenseInstance */

#ifndef _Included_org_moa_gpu_bridge_NativeDenseInstance
#define _Included_org_moa_gpu_bridge_NativeDenseInstance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_gpu_bridge_NativeDenseInstance
 * Method:    writeToNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_NativeDenseInstance_writeToNative
  (JNIEnv *, jobject);

/*
 * Class:     org_moa_gpu_bridge_NativeDenseInstance
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_NativeDenseInstance_release
  (JNIEnv *, jobject);

/*
 * Class:     org_moa_gpu_bridge_NativeDenseInstance
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_NativeDenseInstance_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
