/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_gpu_DenseSGD */

#ifndef _Included_org_moa_gpu_DenseSGD
#define _Included_org_moa_gpu_DenseSGD
#ifdef __cplusplus
extern "C" {
#endif
#undef org_moa_gpu_DenseSGD_serialVersionUID
#define org_moa_gpu_DenseSGD_serialVersionUID 1i64
#undef org_moa_gpu_DenseSGD_HINGE
#define org_moa_gpu_DenseSGD_HINGE 0L
#undef org_moa_gpu_DenseSGD_LOGLOSS
#define org_moa_gpu_DenseSGD_LOGLOSS 1L
#undef org_moa_gpu_DenseSGD_SQUAREDLOSS
#define org_moa_gpu_DenseSGD_SQUAREDLOSS 2L
/*
 * Class:     org_moa_gpu_DenseSGD
 * Method:    getVotesForDenseInstance
 * Signature: (Lorg/moa/gpu/bridge/NativeDenseInstance;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_moa_gpu_DenseSGD_getVotesForDenseInstance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_moa_gpu_DenseSGD
 * Method:    trainNative
 * Signature: (Lorg/moa/gpu/bridge/NativeInstanceBatch;)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_DenseSGD_trainNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_moa_gpu_DenseSGD
 * Method:    initNative
 * Signature: (IIIZDD)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_DenseSGD_initNative
  (JNIEnv *, jobject, jint, jint, jint, jboolean, jdouble, jdouble);

/*
 * Class:     org_moa_gpu_DenseSGD
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_DenseSGD_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
