/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_gpu_bridge_NativeSparseInstance */

#ifndef _Included_org_moa_gpu_bridge_NativeSparseInstance
#define _Included_org_moa_gpu_bridge_NativeSparseInstance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_gpu_bridge_NativeSparseInstance
 * Method:    writeToNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_NativeSparseInstance_writeToNative
  (JNIEnv *, jobject);

/*
 * Class:     org_moa_gpu_bridge_NativeSparseInstance
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_NativeSparseInstance_release
  (JNIEnv *, jobject);

/*
 * Class:     org_moa_gpu_bridge_NativeSparseInstance
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_NativeSparseInstance_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
