/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_gpu_bridge_SparseOffHeapBuffer */

#ifndef _Included_org_moa_gpu_bridge_SparseOffHeapBuffer
#define _Included_org_moa_gpu_bridge_SparseOffHeapBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_gpu_bridge_SparseOffHeapBuffer
 * Method:    allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_moa_gpu_bridge_SparseOffHeapBuffer_allocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_moa_gpu_bridge_SparseOffHeapBuffer
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_SparseOffHeapBuffer_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_moa_gpu_bridge_SparseOffHeapBuffer
 * Method:    nativeBegin
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_SparseOffHeapBuffer_nativeBegin
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_moa_gpu_bridge_SparseOffHeapBuffer
 * Method:    nativeCommit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_SparseOffHeapBuffer_nativeCommit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
