/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_gpu_bridge_NativeInstance */

#ifndef _Included_org_moa_gpu_bridge_NativeInstance
#define _Included_org_moa_gpu_bridge_NativeInstance
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
