/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_gpu_SGD */

#ifndef _Included_org_moa_gpu_SGD
#define _Included_org_moa_gpu_SGD
#ifdef __cplusplus
extern "C" {
#endif
#undef org_moa_gpu_SGD_serialVersionUID
#define org_moa_gpu_SGD_serialVersionUID 1LL
/*
 * Class:     org_moa_gpu_SGD
 * Method:    getVotesForSparseInstance
 * Signature: (JJJJLorg/moa/gpu/BatchInstances;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_moa_gpu_SGD_getVotesForSparseInstance
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jobject);

/*
 * Class:     org_moa_gpu_SGD
 * Method:    getVotesForDenseInstance
 * Signature: (JJLorg/moa/gpu/BatchInstances;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_moa_gpu_SGD_getVotesForDenseInstance
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     org_moa_gpu_SGD
 * Method:    trainNative
 * Signature: (Lorg/moa/gpu/BatchInstances;)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_SGD_trainNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_moa_gpu_SGD
 * Method:    initNative
 * Signature: (IIIZDD)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_SGD_initNative
  (JNIEnv *, jobject, jint, jint, jint, jboolean, jdouble, jdouble);

/*
 * Class:     org_moa_gpu_SGD
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_SGD_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
