/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_moa_gpu_bridge_DenseOffHeapBuffer */

#ifndef _Included_org_moa_gpu_bridge_DenseOffHeapBuffer
#define _Included_org_moa_gpu_bridge_DenseOffHeapBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_moa_gpu_bridge_DenseOffHeapBuffer
 * Method:    allocate
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_moa_gpu_bridge_DenseOffHeapBuffer_allocate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_moa_gpu_bridge_DenseOffHeapBuffer
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_DenseOffHeapBuffer_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_moa_gpu_bridge_DenseOffHeapBuffer
 * Method:    begin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_DenseOffHeapBuffer_begin
  (JNIEnv *, jobject);

/*
 * Class:     org_moa_gpu_bridge_DenseOffHeapBuffer
 * Method:    commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_moa_gpu_bridge_DenseOffHeapBuffer_commit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
