/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class weka_core_Instance */

#ifndef _Included_weka_core_Instance
#define _Included_weka_core_Instance
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
